---
kind: pipeline
name: alpine
steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: xsteadfastx/tox-python
      dockerfile: Dockerfile.alpine
      tags:
        - alpine
        - minimal
        - slim
---
kind: pipeline
name: ubuntu
steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: xsteadfastx/tox-python
      dockerfile: Dockerfile.ubuntu
      tags:
        - ubuntu
        - full
